### ISSUE TITLE
Incorrect identification of folders

### ISSUE THREAD

**Issue by DanielKnerr** [Daanisaanwezig/Discord-Radio#16]
### Current behavior
The bot only uses `fs.existsSync` as a check before accessing folders:
https://github.com/Daanisaanwezig/Discord-Radio/blob/2ac4495adf4a924f0feae1faf69bdcb55a06bf5b/src/commands/music/stations.ts#L16-L18

This is incorrect, because `fs.existsSync` only checks if the **path** exists, but not if the path refers to a folder. No checks are done when accessing the *contents* of the `music` folder:

https://github.com/Daanisaanwezig/Discord-Radio/blob/2ac4495adf4a924f0feae1faf69bdcb55a06bf5b/src/commands/music/play.ts#L103-L106

This issue results in three bugs:
1. a crash with an `ENOTDIR` error if the `music` "folder" is actually a file
2. an `ENOTDIR` error (without crashing) without a proper error-message when trying to play a station that exists, but isn't a folder
3. listing *everything* (including files) in the `music` folder when executing `/stations`

### Expected behavior
The bot should (in the order of the bugs listed above):
1. not crash, but instead tell the user that the `music` folder is missing.
2. not generate an error
3. only list folders inside the `music` folder as stations

### How to reproduce this bug
Bug 1 can be reproduced by:
- replacing the `music` folder with a file named `music`
- executing the `/stations` command

Bugs 2 and 3 can be reproduced by:
- adding a file `test` to the music folder
- executing `/stations`
- executing `/play station:test`

**Comment by DanielKnerr** [comment]
I propose creating a utility function `folderExists(path: string): boolean` that checks if the given path refers to a folder and using this function instead of `fs.existsSync`. This function should also be used before accessing the contents of the `music` folder.

**Comment by Daanisaanwezig** [comment]
Thanks for reporting this bug, I think it indeed is a good idea to implement what you propose.
Would you like to pick up this issue?

**Comment by DanielKnerr** [comment]
Yes, I would like to!

**Comment by Daanisaanwezig** [comment]
Okay, I assigned you to this issue.
