### ISSUE TITLE
Bug: nowplaying command doesn't work as expected after stopping music

### ISSUE THREAD

**Issue by N-Shar-ma** [Daanisaanwezig/Discord-Radio#19]
## Current Behaviour

![image](https://user-images.githubusercontent.com/68962290/135842210-f4fcaf2d-d971-4424-9d8b-6de7b33b1d20.png)

After stopping the music, and then running the `/nowplaying` command, it shows the last played (and now stopped) track as the one being currently playing

## Expected Behaviour

The bot should reply to the `/nowplaying` command saying there is no song currently being played

## How to Reproduce the Bug

Run the following commands in order:
- `/play {station}`
- `/stop`
-  `/nowplaying`

**Comment by Daanisaanwezig** [comment]
This is most likely a duplicate of #1, the song that is being played is being pulled from the status of the bot which as of now doesn't get cleared.

**Comment by Croustys** [comment]
Yes, as Daan said, it is duplicate of #1 . Will be working fine as soon as the person, who was assigned with the issue submits the correct PR.
