### ISSUE TITLE
Station name length

### ISSUE THREAD

**Issue by DanielKnerr** [Daanisaanwezig/Discord-Radio#20]
As discussed in the comments of PR #17, station names that are too long can cause compatibility issues with the Discord API. 

While most operating systems limit the name of a folder to 255 characters, Discord usually imposes stricter limits on the length of fields. By browsing the Discord API it appears that 100 characters is a common limit. To ensure compatibility (now and in the future) we should limit the length a station name is allowed to be (preferably with some buffer so we can add additional data into the field).

I imagine that most users would use short names for their playlists, so a limit like 50 characters shouldn't interfere with the user-experience.

**Comment by Daanisaanwezig** [comment]
Agreed, 50 characters seems like a good limit to me.

How would this limit be enforced? Will the bot not start if the music folder contains folders with a name longer than 50 characters or do you have a better solution in mind?

**Comment by N-Shar-ma** [comment]
Just adding my 2 cents: whenever the station option in the `/play` command is over 50 characters long, the bot should maybe inform the user that station names over 50 characters are not permitted, and urge them to ensure that their station/folders are named accordingly.

**Comment by DanielKnerr** [comment]
*In general*, I believe it would be a good idea to separate command-execution and file system access, by refactoring all code that's accessing the file-system into separate functions. That way we can verify if a requested station name is valid in a central place, without repeating the same code for every command.

Regardless of that, I thank that extending the `folderExists` function to also check the length of the requested folder is probably the easiest solution.

**Comment by Daanisaanwezig** [comment]
> _In general_, I believe it would be a good idea to separate command-execution and file system access, by refactoring all code that's accessing the file-system into separate functions. That way we can verify if a requested station name is valid in a central place, without repeating the same code for every command.
> 
> Regardless of that, I thank that extending the `folderExists` function to also check the length of the requested folder is probably the easiest solution.

This does indeed sound like the most logical thing to do, keeping it central is always a good thing to do.



> Just adding my 2 cents: whenever the station option in the `/play` command is over 50 characters long, the bot should maybe inform the user that station names over 50 characters are not permitted, and urge them to ensure that their station/folders are named accordingly.

A message letting the user know that the character limit is exceeded on a name is always a nice thing to have, so I'd say this should be implemented but again in a centralized way so that you don't need to change it in every single file if we want to change something later on.

**Comment by DanielKnerr** [comment]
I am going to code up an example of what I imagine, otherwise it would be a lot of work to explain all the little details in text :)

@Daanisaanwezig, can you please assign me to this issue?
