### ISSUE TITLE
Bug: Switch station button crashes bot when it is being pressed by someone not in a voice channel

### ISSUE THREAD

**Issue by Daanisaanwezig** [Daanisaanwezig/Discord-Radio#29]
### Current behavior
When the person pressing the switch station button is not in a voice channel it crashes the bot.

### Expected behavior
The bot should notify the user that you have to be in a voice channel when running the command.

### How to reproduce this bug
Run the play command to switch radio station to get the prompt with the button, leave the channel and press the button.

Note: This issue also hooks into #28 since it also regards the usage of buttons in this case by people who did not run the command.

**Comment by stijnvdkolk** [comment]
Can I also take this one? @Daanisaanwezig

**Comment by Daanisaanwezig** [comment]
> Can I also take this one? @Daanisaanwezig 

Sure thing, I will assign you to both issues.
