### ISSUE TITLE
Add how-to-host.md

### ISSUE THREAD

**Issue by Daanisaanwezig** [Daanisaanwezig/Discord-Radio#4]
### Feature request
Currently there is no text tutorial on how to host the bot, a file should be added that explains all the steps needed to host the bot yourself, it should also mention the need of external programs like Node.js.
This file should be located in the root directory and be pointed to in the README.md.

Adding a how-to-host.md will make it easier for other people to host the bot without much knowledge about Discord bots or development in Node.js.

**Comment by Victoria-DR** [comment]
Hi there, I'd like to help out with this.

**Comment by ritviksharma3** [comment]
Hi, I can help you with this.

**Comment by Victoria-DR** [comment]
To clarify, should the file consist of how to start up the bot locally on your own computer?

**Comment by Daanisaanwezig** [comment]
> To clarify, should the file consist of how to start up the bot locally on your own computer?

Yes, the file should give a rundown describing all steps needed to get the bot running locally on your computer.
So things like installing Node.js, creating a Discord bot and inviting it, downloading the latest build and changing the configuration files.

I will assign both of you to the issue, don't feel discouraged if you are not the first one to create a PR, if the how-to-host.md looks good I will give it the `hacktoberfest-accepted` label so that it still counts towards completing the Hacktoberfest challenge.

If there is any other information you need or questions you have feel free to ask them.
