### ISSUE TITLE
New command: /stations

### ISSUE THREAD

**Issue by Daanisaanwezig** [Daanisaanwezig/Discord-Radio#8]
### Feature request
Add a `/stations` command that displays all radio stations that are available, this should be automatically generated by checking for sub folders in the music folder.
This is useful for when not all radio stations are known allowing the user to get a list of all of them.

**Comment by adryan30** [comment]
I can work on this issue! But can you kindly add the hacktoberfest label to it?

**Comment by Daanisaanwezig** [comment]
I will assign you to the issue.
Also there is no need to add the label, the repository has the hacktoberfest topic so any pull request made to this repository will count. If there is another reason why you want the label to be added feel free to let me know.
